# Generated by Django 4.1.3 on 2023-02-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQuotaResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.quota')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.request')),
            ],
        ),
    ]
