# Generated by Django 4.1.3 on 2023-02-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='datecode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
