# Generated by Django 4.1.3 on 2023-02-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_requestquotaresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='brand',
        ),
    ]
