# Generated by Django 4.1.3 on 2023-02-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_quote_datecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parts',
        ),
    ]
