# Generated by Django 4.1.3 on 2023-02-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_request_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
