# Generated by Django 4.1.3 on 2023-02-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0008_alter_quota_part_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='part_number',
            new_name='part',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='part_number',
            new_name='part',
        ),
        migrations.AddField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
