# Generated by Django 4.1.3 on 2023-02-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_rename_part_number_quota_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquotaresult',
            name='rubble_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
