# Generated by Django 4.1.3 on 2023-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_requestquotaresult_rubble_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestquotaresult',
            name='rubble_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
