# Generated by Django 4.1.3 on 2023-02-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_alter_requestquotaresult_rubble_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='requestquotaresult',
            name='rubble_price',
        ),
    ]
