# Generated by Django 4.1.3 on 2023-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_remove_quota_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
