# Generated by Django 4.1.3 on 2023-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_alter_quota_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='datecode',
            field=models.PositiveIntegerField(default=2020),
            preserve_default=False,
        ),
    ]
