# Generated by Django 4.1.3 on 2023-02-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0014_quota_datecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='selected_quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_quotas', to='parts.quota'),
        ),
        migrations.CreateModel(
            name='ResponseQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.request')),
            ],
        ),
    ]
