# Generated by Django 4.1.3 on 2023-02-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_request_selected_quota_responsequota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseQuota',
        ),
    ]
