# Generated by Django 4.1.3 on 2023-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_request_customer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='customer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
