# Generated by Django 4.1.3 on 2023-02-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_alter_request_customer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='package_type',
            field=models.CharField(default='Заполни упаковку!', max_length=50, null=True),
        ),
    ]
