# Generated by Django 4.1.3 on 2023-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_part_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='package_type',
        ),
        migrations.AddField(
            model_name='part',
            name='case_type',
            field=models.CharField(default='Заполни корпус!', max_length=50, null=True),
        ),
    ]
