# Generated by Django 4.1.3 on 2023-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_quota_lead_time_quota_ruble_price_alter_quota_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'verbose_name': 'Квота', 'verbose_name_plural': 'Квоты'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро'), ('RUB', 'Рубль')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
