# Generated by Django 4.1.3 on 2023-02-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0024_alter_requestquotaresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('QUOTA', 'Quota'), ('NO_QUOTA', 'No Quota'), ('PAID', 'Paid'), ('ORDERED', 'Ordered')], default='NO_QUOTA', max_length=10),
        ),
        migrations.AlterField(
            model_name='quota',
            name='date',
            field=models.DateField(verbose_name='Дата квоты'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='datecode',
            field=models.PositiveIntegerField(verbose_name='DC'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='lead_time',
            field=models.CharField(max_length=100, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='request',
            name='currency',
            field=models.CharField(choices=[('USD', 'Доллар'), ('EUR', 'Евро'), ('RUB', 'Рубль')], default='RUB', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer',
            field=models.CharField(max_length=100, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='request',
            name='customer_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(verbose_name='Дата запроса'),
        ),
        migrations.AlterField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='request',
            name='selected_quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_quotas', to='parts.quota'),
        ),
        migrations.AlterField(
            model_name='requestquotaresult',
            name='ruble_air_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Авиа'),
        ),
        migrations.AlterField(
            model_name='requestquotaresult',
            name='ruble_sea_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Морем'),
        ),
    ]
